import React from 'react'
import PropTypes from 'prop-types'
import Head from 'next/head'

export const MetaSeo = (props) => {
  return (
    <Head>
      <title>Nguyen Hoang Thien Khai</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
