import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from 'styles/Home.module.css'
import useTrans from 'common/hooks/useTrans'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import { getAllProducts } from 'stores/apps/productSlice'
// import 'aos/dist/aos.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dispath = useDispatch()
  const trans = useTrans()

  useEffect(() => {
    dispath(getAllProducts())
  }, [dispath])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="bg-black h-[100vh]"></div>
      <div className="flex flex-col items-center gap-[20px]">
        <div className="h-[100vh] flex items-center justify-center">
          <div className="w-[200px] h-[200px] bg-slate-400 " data-aos="fade-up">
            a
          </div>
        </div>
        <div
          className="h-[100vh] flex items-center justify-center"
          data-aos="fade-up"
        >
          <div className="w-[200px] h-[200px] bg-slate-400 ">b</div>
        </div>
        <div className="h-[100vh] flex items-center justify-center">
          <div className="w-[200px] h-[200px] bg-slate-400 " data-aos="fade-up">
            c
          </div>
        </div>
      </div> */}
    </>
  )
}
